version: '3.4'

services:

  webapp:
    image: taskmanager-webapp
    restart: on-failure
    build:
      context: .
      dockerfile: TaskManagerApp/Dockerfile
    ports: 
      - 8181:80
    environment: 
      - ConnectionStrings__TaskManagerAppContext=Server=mssql;Database=taskmanagerdb;User Id=sa;Password=a3uK4vgJHnk7mxBAyUHnnLBm
    depends_on:
      - mssql

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=a3uK4vgJHnk7mxBAyUHnnLBm
      - MSSQL_PID=Developer
